spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5433/auth
    username: admin
    password: pass
    hikari:
      read-only: ${DB_READ_ONLY:false}

#  datasource:
#    url: jdbc:h2:mem:backend2
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect

    #    for H2
#    database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true

#  h2:
#    console:
#      enabled: true

  liquibase:
    enabled: true
    show-summary-output: console

  output:
    ansi:
      enabled: always

server:
  port: 9998
  forward-headers-strategy: framework

grpc:
  server:
    port: 9090

jwt:
  secretKey: 1234567890qwerty1234567890qwerty  # need more 256 bit. NEED SECURE VAULT TO SAVE
  expiration: 3600000                       # 1 hour

logging:
  level:
    liquibase: debug
    com.edu.authservise: debug
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug


