services:

#  DB

  postgres:
    image: postgres:latest
    container_name: pg_backend_2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: backend2
    ports:
      - "5432:5432"
    volumes:
      - ./shop-service/src/main/resources/psql_map_folder:/psql_map_folder
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d backend2" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - backend_network

  postgres_auth:
    image: postgres:latest
    container_name: db_pg_auth
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: auth
    ports:
      - "5433:5432"
#    volumes:
#      - ./auth-service/src/main/resources/psql_map_folder:/psql_map_folder
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d auth" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - backend_network

#    DB ADMIN SERVICE

  adminer:
    image: dpage/pgadmin4
    container_name: pg_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:80/misc/ping"]
      interval: 10s         # Как часто выполнять проверку
      timeout: 10s          # Сколько ждать ответа
      retries: 5            # Сколько раз повторить проверку до признания контейнера unhealthy
      start_period: 10s     # Период ожидания перед началом проверок
    restart: unless-stopped
    networks:
      - backend_network

#    BACKEND SERVICES

  auth_service:
    image: auth-service:latest
    container_name: auth_service
#    ports:
#      - "9090:9090"
    depends_on:
      postgres_auth:
        condition: service_healthy
    restart: unless-stopped
    networks:
      backend_network:
        ipv4_address: 192.168.1.100

  shop_service_primary:
    image: shop-service:latest
    container_name: shop_service_primary
    ports:
      - "9999:9999"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_READ_ONLY: false
      GRPC_CLIENT_AUTHGRPCCLIENT_ADDRESS: static://192.168.1.100:9090
    restart: unless-stopped
    networks:
      - backend_network

  shop_service_db_ro-1:
    image: shop-service:latest
    container_name: shop_service_db_ro-1
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_READ_ONLY: true
      GRPC_CLIENT_AUTHGRPCCLIENT_ADDRESS: static://192.168.1.100:9090
    restart: unless-stopped
    networks:
      - backend_network

  shop_service_db_ro-2:
    image: shop-service:latest
    container_name: shop_service_db_ro-2
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_READ_ONLY: true
      GRPC_CLIENT_AUTHGRPCCLIENT_ADDRESS: static://192.168.1.100:9090
    restart: unless-stopped
    networks:
      - backend_network

# REVERS PROXY NGINX

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./shop-service/src/main/resources/static/nginx:/static
      - ./shop-service/src/main/resources/cert:/certs/
    depends_on:
      shop_service_primary:
        condition: service_started
      adminer:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24