#version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: pg_backend_2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: backend2
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/psql_map_folder:/psql_map_folder
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d backend2" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: backend:latest
    container_name: backend
    ports:
      - "9999:9999"
    depends_on:
      postgres:
        condition: service_healthy
