services:

  #  DB

  postgres:
    image: postgres:latest
    container_name: pg_backend_2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: backend2
    ports:
      - "5432:5432"
    volumes:
      - ./shop-service/src/main/resources/psql_map_folder:/psql_map_folder
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d backend2" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - backend_network

  postgres_auth:
    image: postgres:latest
    container_name: db_pg_auth
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: auth
    ports:
      - "5433:5432"
    #    volumes:
    #      - ./auth-service/src/main/resources/psql_map_folder:/psql_map_folder
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d auth" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - backend_network

  #    DB ADMIN SERVICE

  adminer:
    image: dpage/pgadmin4
    container_name: pg_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    healthcheck:
      test: [ "CMD", "wget", "-O", "-", "http://localhost:80/misc/ping" ]
      interval: 10s         # Как часто выполнять проверку
      timeout: 10s          # Сколько ждать ответа
      retries: 5            # Сколько раз повторить проверку до признания контейнера unhealthy
      start_period: 10s     # Период ожидания перед началом проверок
    restart: unless-stopped
    networks:
      - backend_network

  #    BACKEND SERVICES

  auth_service:
    image: auth-service:latest
    container_name: auth_service
    environment:
      POSTGRES_AUTH_URL: jdbc:postgresql://postgres_auth:5432/auth
    #    ports:
    #      - "9090:9090"
    depends_on:
      postgres_auth:
        condition: service_healthy
    restart: unless-stopped
    networks:
      backend_network:
        ipv4_address: 192.168.1.100

  shop_service_primary:
    image: shop-service:latest
    container_name: shop_service_primary
    ports:
      - "9999:9999"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_READ_ONLY: false
      GRPC_CLIENT_AUTHGRPCCLIENT_ADDRESS: static://192.168.1.100:9090
    restart: unless-stopped
    networks:
      - backend_network

  shop_service_db_ro-1:
    image: shop-service:latest
    container_name: shop_service_db_ro-1
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_READ_ONLY: true
      GRPC_CLIENT_AUTHGRPCCLIENT_ADDRESS: static://192.168.1.100:9090
    restart: unless-stopped
    networks:
      - backend_network

  shop_service_db_ro-2:
    image: shop-service:latest
    container_name: shop_service_db_ro-2
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_READ_ONLY: true
      GRPC_CLIENT_AUTHGRPCCLIENT_ADDRESS: static://192.168.1.100:9090
    restart: unless-stopped
    networks:
      - backend_network

  # REVERS PROXY NGINX

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./shop-service/src/main/resources/static/nginx:/static
      - ./shop-service/src/main/resources/cert:/certs/
    depends_on:
      shop_service_primary:
        condition: service_started
      adminer:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend_network

  #MESSEGING

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
#    depends_on:
#      - zookeeper
    ports:
      - "29092:29092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_LISTENERS=CONTROLLER://:9093,PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CONTROLLER://kafka:9093,PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
#    volumes:
#      - .kafka-data:/bitnami/kafka:z
    networks:
      - kafka-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=LocalCluster
      # Список брокеров для доступа изнутри Docker-сети
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    networks:
      - kafka-net


networks:
  backend_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
  kafka-net:
    driver: bridge

#volumes:
#  kafka-data:
#    driver: local