version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: pg_backend_2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: backend2
    ports:
      - "5432:5432"
    volumes:
      - src/main/resources/psql_map_folder/product_images:/psql_map_folder