version: '3.8'  # Укажите версию Docker Compose

services:
  postgres:
    image: postgres:latest  # Используйте последнюю версию образа PostgreSQL
    container_name: pg_backend_2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: backend2
    ports:
      - "5432:5432"  # Проброс порта
    volumes:
      - G:\workdir\21-school\backend\backend_2\backend_2\src\main\resources\psql_map_folder:/psql_map_folder
#    restart: no  # Опционально: перезапускать контейнер при сбоях
