spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/backend2
    username: admin
    password: pass

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  liquibase:
    enabled: true


server:
  port: 9999
