spring:
  application:
    name: event-service

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  #      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  output:
    ansi:
      enabled: always

server:
  port: 9997

kafka:
  out:
    product:
      updates-stocks:
        topic: product-updates-stocks

rest:
  client:
    shop-service:
      product:
        all:
          url: ${product-all-url:/api/v1/product/all}

scheduler:
  product:
    updates-stocks: 10000


logging:
  level:
    liquibase: info
    com.edu.eventservice: debug
