spring:
  application:
    name: event-service

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  #      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  output:
    ansi:
      enabled: always

server:
  port: 9997

kafka:
  out:
    product:
      updates-stocks:
        topic: product-stock-update-event-request
      updates-price:
        topic: product-price-update-event-request
  in:
    product:
      update-event:
        topic: product-update-event-response
        group-id: product-update-event-response-event-group
      update-stock-event:
        topic: product-stock-update-event-response
        group-id: product-stock-update-event-response-event-group
      update-price-event:
        topic: product-price-update-event-response
        group-id: product-price-update-event-response-event-group

rest:
  client:
    shop-service:
      product:
        all:
          url: ${product-all-url:/api/v1/product/all}

scheduler:
  product:
    updates-stocks: 10000
    updates-price: 20000


logging:
  level:
    liquibase: info
    com.edu.eventservice: debug
